spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: postgres
  messages:
    basename: ValidationMessages
  sql:
    init:
      mode: always
